
export enum AppMode {
  NONE = 'NONE',
  STARTUP = 'STARTUP',
  EXISTING = 'EXISTING'
}

export enum ToolType {
  // Common
  DASHBOARD = 'DASHBOARD',
  TOTAL_BRAND_ARCHITECT = 'TOTAL_BRAND_ARCHITECT', // New All-in-One Tool
  
  // Startup
  BRAND_DISCOVERY = 'BRAND_DISCOVERY',
  BUSINESS_BLUEPRINT = 'BUSINESS_BLUEPRINT',
  BRAND_SIMULATOR = 'BRAND_SIMULATOR', // Strategy Simulator
  BRAND_EVOLUTION = 'BRAND_EVOLUTION', // New Evolution Tool
  CUSTOMER_OBJECTIONS = 'CUSTOMER_OBJECTIONS', // New Objection Tool
  TRUST_BUILDER = 'TRUST_BUILDER', // New Trust Tool
  DECISION_CRITIC = 'DECISION_CRITIC', // New Critic Tool
  DIFFERENTIATION_GENERATOR = 'DIFFERENTIATION_GENERATOR', // New Differentiation Tool
  FAILURE_ANALYSIS = 'FAILURE_ANALYSIS', // Pre-Mortem Tool
  INVESTOR_PITCH = 'INVESTOR_PITCH', // Pitch Tool
  COMPETITOR_ANALYSIS = 'COMPETITOR_ANALYSIS', // Competitor Tool
  CUSTOMER_PSYCHOLOGY = 'CUSTOMER_PSYCHOLOGY', // Psychology Tool
  CULTURAL_ALIGNMENT = 'CULTURAL_ALIGNMENT', // New Cultural Tool
  AUTO_BRAND_BUILDER = 'AUTO_BRAND_BUILDER',
  BUSINESS_ECOSYSTEM = 'BUSINESS_ECOSYSTEM',
  TENANT_MIX_OPTIMIZER = 'TENANT_MIX_OPTIMIZER',
  EDUCATIONAL_AGREEMENT_INSIGHTS = 'EDUCATIONAL_AGREEMENT_INSIGHTS',
  LEGAL_CHECKLIST = 'LEGAL_CHECKLIST',
  FINANCIAL_RISK_OVERVIEW = 'FINANCIAL_RISK_OVERVIEW',
  NAME_GENERATOR = 'NAME_GENERATOR',
  TAGLINE_GENERATOR = 'TAGLINE_GENERATOR',
  BRAND_PERSONALITY = 'BRAND_PERSONALITY',
  EMOTIONAL_STRATEGY = 'EMOTIONAL_STRATEGY',
  VISUAL_IDENTITY = 'VISUAL_IDENTITY',
  LAUNCH_CAMPAIGN = 'LAUNCH_CAMPAIGN',
  SOCIAL_HYPE_CALENDAR = 'SOCIAL_HYPE_CALENDAR',
  WEBSITE_COPY_GENERATOR = 'WEBSITE_COPY_GENERATOR',
  PRICING_STRATEGY = 'PRICING_STRATEGY',
  COLOR_PALETTE = 'COLOR_PALETTE',
  MULTI_CHANNEL_ADAPTER = 'MULTI_CHANNEL_ADAPTER',
  
  // Existing
  BRAND_AUDIT = 'BRAND_AUDIT',
  IDENTITY_REFRESH = 'IDENTITY_REFRESH',
  PRODUCT_DESCRIPTION = 'PRODUCT_DESCRIPTION',
  MARKETING_WRITER = 'MARKETING_WRITER',
  CONTENT_REFINERY = 'CONTENT_REFINERY',
  DOCUMENT_SUMMARIZER = 'DOCUMENT_SUMMARIZER',
  BRAND_RATIONALE = 'BRAND_RATIONALE',
  SENTIMENT_ANALYSIS = 'SENTIMENT_ANALYSIS',
  BRAND_CONSULTANT = 'BRAND_CONSULTANT'
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: Date;
}

export interface SentimentData {
  category: string;
  count: number;
  fill: string;
}

export interface GeneratedAsset {
  id: string;
  type: 'text' | 'image' | 'json';
  content: string;
  meta?: string; // e.g., prompt used or title
}